import { IClothing } from './types/clothing.interface';

export const mockClothingItems: IClothing[] = [
  {
    id: '1',
    title: 'Куртки',
    brand: 'Pull&Bear',
    category: 'Плечевая одежда',
    subCategory: 'Куртки',
    colors: ['Красный'],
    seasons: ['Весна', 'Осень'],
    notes: 'Красная куртка',
    storageLocation: 'Шкаф, полка 2',
    shopLink: 'https://www.pullandbear.com/ru/ru/jacket-red',
    price: '',
    images: ['https://i.imgur.com/X9n2h0c.png'],
    inFittingRoom: false,
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-01-15T10:30:00Z',
  },
  {
    id: '2',
    title: 'Джинсы',
    brand: 'Levi\'s',
    category: 'Поясная одежда',
    subCategory: 'Джинсы',
    colors: ['Синий'],
    seasons: ['Весна', 'Лето', 'Осень'],
    notes: '',
    storageLocation: 'Шкаф, полка 1',
    shopLink: '',
    price: '',
    images: ['https://i.imgur.com/MuxglEl.jpg'],
    inFittingRoom: true,
    createdAt: '2024-01-14T14:20:00Z',
    updatedAt: '2024-01-14T14:20:00Z',
  },
  {
    id: '3',
    title: 'Свитеры',
    brand: 'Massimo Dutti',
    category: 'Плечевая одежда',
    subCategory: 'Свитеры',
    colors: ['Белый'],
    seasons: ['Зима'],
    notes: '',
    storageLocation: 'Комод, ящик 3',
    shopLink: '',
    price: '',
    images: ['https://i.imgur.com/faBEtqt.jpg'],
    inFittingRoom: false,
    createdAt: '2024-01-13T09:15:00Z',
    updatedAt: '2024-01-13T09:15:00Z',
  },
  {
    id: '4',
    title: 'Платья',
    brand: 'Zara',
    category: 'Плечевая одежда',
    subCategory: 'Платья',
    colors: ['Чёрный'],
    seasons: ['Лето'],
    notes: '',
    storageLocation: 'Шкаф, полка 4',
    shopLink: '',
    price: '',
    images: ['https://i.imgur.com/FNcrIV9.jpg'],
    inFittingRoom: true,
    createdAt: '2024-01-12T16:45:00Z',
    updatedAt: '2024-01-12T16:45:00Z',
  },
  {
    id: '5',
    title: 'Джемперы',
    brand: 'H&M',
    category: 'Плечевая одежда',
    subCategory: 'Джемперы',
    colors: ['Серый'],
    seasons: ['Осень', 'Зима'],
    notes: '',
    storageLocation: 'Комод, ящик 2',
    shopLink: '',
    price: '',
    images: ['https://i.imgur.com/faBEtqt.jpg'],
    inFittingRoom: false,
    createdAt: '2024-01-11T11:10:00Z',
    updatedAt: '2024-01-11T11:10:00Z',
  },
  {
    id: '6',
    title: 'Юбки',
    brand: 'Mango',
    category: 'Поясная одежда',
    subCategory: 'Юбки',
    colors: ['Бежевый'],
    seasons: ['Весна', 'Лето'],
    notes: '',
    storageLocation: 'Шкаф, полка 3',
    shopLink: '',
    price: '',
    images: ['https://i.imgur.com/jdQC3LD.jpg'],
    inFittingRoom: false,
    createdAt: '2024-01-10T13:25:00Z',
    updatedAt: '2024-01-10T13:25:00Z',
  },
  {
    id: '7',
    title: 'Рубашки',
    brand: 'COS',
    category: 'Плечевая одежда',
    subCategory: 'Рубашки',
    colors: ['Белый'],
    seasons: ['Весна', 'Лето'],
    notes: '',
    storageLocation: 'Шкаф, полка 1',
    shopLink: '',
    price: '',
    images: ['https://i.imgur.com/HNz6ru5.jpg'],
    inFittingRoom: false,
    createdAt: '2024-01-09T08:40:00Z',
    updatedAt: '2024-01-09T08:40:00Z',
  },
  {
    id: '8',
    title: 'Обувь',
    brand: 'New Balance',
    category: 'Обувь',
    subCategory: 'Кроссовки',
    colors: ['Серый'],
    seasons: ['Весна', 'Лето', 'Осень'],
    notes: '',
    storageLocation: 'Коробка в прихожей',
    shopLink: '',
    price: '',
    images: ['https://i.imgur.com/HNz6ru5.jpg'],
    inFittingRoom: false,
    createdAt: '2024-01-08T15:55:00Z',
    updatedAt: '2024-01-08T15:55:00Z',
  },
  {
    id: '9',
    title: 'Пальто',
    brand: 'Reserved',
    category: 'Верхняя одежда',
    subCategory: 'Пальто',
    colors: ['Чёрный'],
    seasons: ['Осень', 'Зима'],
    notes: '',
    storageLocation: 'Шкаф, полка 5',
    shopLink: '',
    price: '',
    images: ['https://i.imgur.com/fqgndLC.jpg'],
    inFittingRoom: true,
    createdAt: '2024-01-07T12:05:00Z',
    updatedAt: '2024-01-07T12:05:00Z',
  },
  {
    id: '10',
    title: 'Блузки',
    brand: 'Bershka',
    category: 'Плечевая одежда',
    subCategory: 'Блузки',
    colors: ['Белый'],
    seasons: ['Весна', 'Лето'],
    notes: '',
    storageLocation: 'Комод, ящик 1',
    shopLink: '',
    price: '',
    images: ['https://i.imgur.com/cvzkASV.jpg'],
    inFittingRoom: false,
    createdAt: '2024-01-06T10:20:00Z',
    updatedAt: '2024-01-06T10:20:00Z',
  },
  {
    id: '11',
    title: 'Брюки',
    brand: 'Zara',
    category: 'Поясная одежда',
    subCategory: 'Брюки',
    colors: ['Чёрный'],
    seasons: ['Весна', 'Осень'],
    notes: '',
    storageLocation: 'Шкаф, полка 2',
    shopLink: '',
    price: '',
    images: ['https://i.imgur.com/Gc25Cm1.jpg'],
    inFittingRoom: false,
    createdAt: '2024-01-05T14:35:00Z',
    updatedAt: '2024-01-05T14:35:00Z',
  },
  {
    id: '12',
    title: 'Пиджаки',
    brand: 'Mango',
    category: 'Плечевая одежда',
    subCategory: 'Пиджаки',
    colors: ['Серый'],
    seasons: ['Весна', 'Осень'],
    notes: '',
    storageLocation: 'Шкаф, полка 4',
    shopLink: '',
    price: '',
    images: ['https://i.imgur.com/Gc25Cm1.jpg'],
    inFittingRoom: false,
    createdAt: '2024-01-04T09:50:00Z',
    updatedAt: '2024-01-04T09:50:00Z',
  },
];